export const cityNameList = [
    'abramów',
    'adamów',
    'adamówka',
    'albigowa',
    'aleksandrów',
    'aleksandrów kujawski',
    'aleksandrów łódzki',
    'alwernia',
    'ameryka',
    'andrespol',
    'andrychów',
    'annopol',
    'augustów',
    'babiak',
    'babica',
    'babice',
    'babimost',
    'baborów',
    'baboszewo',
    'babsk',
    'bachowice',
    'baćkowice',
    'balice',
    'baligród',
    'balin',
    'bałtów',
    'banie',
    'banie mazurskie',
    'banino',
    'baniocha',
    'baranowo',
    'baranów',
    'baranów sandomierski',
    'barciany',
    'barcin',
    'barczewo',
    'bardo',
    'barlinek',
    'bartniczka',
    'bartoszyce',
    'baruchowo',
    'barwałd górny',
    'barwałd średni',
    'barwice',
    'batorz',
    'bażanowice',
    'bąków',
    'bedlno',
    'bejsce',
    'belsk duży',
    'bełchatów',
    'bełk',
    'bełsznica',
    'bełżec',
    'bełżyce',
    'besko',
    'bestwina',
    'bestwinka',
    'bębło',
    'bęczarka',
    'będków',
    'będzin',
    'będzino',
    'bialowieza',
    'biała',
    'biała piska',
    'biała podlaska',
    'biała poduchowna',
    'biała rawska',
    'białaczów',
    'białe błota',
    'białka',
    'białka tatrzańska',
    'białobrzegi',
    'białogard',
    'białośliwie',
    'białowieża',
    'biały bór',
    'biały dunajec',
    'biały szarlej',
    'białystok',
    'biecz',
    'bielany',
    'bielany wrocławskie',
    'bielawa',
    'bielawy',
    'bielice',
    'bieliny',
    'bielsk',
    'bielsk podlaski',
    'bielsko county',
    'bielsko-biala',
    'bielsko-biała',
    'bieniewice',
    'bieńkówka',
    'bierawa',
    'bierdzany',
    'biertułtowy',
    'bieruń',
    'bierutów',
    'bierzwnik',
    'bieżuń',
    'biłgoraj',
    'binarowa',
    'binków',
    'bircza',
    'biskupice radłowskie',
    'biskupiec',
    'biszcza',
    'bisztynek',
    'blachownia',
    'bledzew',
    'blizanów',
    'blizne',
    'bliżyn',
    'błaszki',
    'błażowa',
    'błądzikowo',
    'błędów',
    'błonie',
    'bobolice',
    'bobowa',
    'bobowo',
    'bobrowice',
    'bobrowniki',
    'bobrowo',
    'bochnia',
    'boćki',
    'bodzanów',
    'bodzechów',
    'bodzentyn',
    'bogatynia',
    'bogdaniec',
    'bogoria',
    'boguchwała',
    'bogucin mały',
    'boguszów-gorce',
    'boguty-pianki',
    'bojadła',
    'bojano',
    'bojanowo',
    'bojanowo stare',
    'bojanów',
    'bojszowy',
    'bojszowy nowe',
    'bolechowice',
    'bolesław',
    'bolesławiec',
    'boleszkowice',
    'bolęcin',
    'bolimów',
    'bolków',
    'bolszewo',
    'boniewo',
    'borek',
    'borek wielkopolski',
    'borki',
    'borkowice',
    'borne sulinowo',
    'boronów',
    'borowa',
    'borowie',
    'borowno',
    'borów',
    'borówki',
    'borucin',
    'borzechów',
    'borzęcin',
    'borzęta',
    'borzytuchom',
    'bozkow',
    'bralin',
    'branice',
    'braniewo',
    'brańsk',
    'brańszczyk',
    'brąszewice',
    'brdów',
    'brenna',
    'brenno',
    'brochów',
    'brodła',
    'brodnica',
    'brodniki',
    'brody',
    'brody-parcele',
    'brojce',
    'brok',
    'broniszewice',
    'bronów',
    'brójce',
    'brudzeń duży',
    'brudzew',
    'brusy',
    'brwinów',
    'brzączowice',
    'brzeg',
    'brzeg dolny',
    'brzesko',
    'brzeszcze',
    'brześć kujawski',
    'brzezinka',
    'brzeziny',
    'brzeziny śląskie',
    'brzeźnica',
    'brzeźnio',
    'brzostek',
    'brzozie',
    'brzozowica',
    'brzozów',
    'brzóza królewska',
    'brzóza stadnicka',
    'brzuze',
    'brzyska',
    'buczek',
    'buczkowice',
    'budziszewice',
    'budzów',
    'budzyń',
    'bugaj',
    'bujaków',
    'buk',
    'bukowiec',
    'bukowina tatrzańska',
    'bukowno',
    'bukowsko',
    'bulkowo',
    'bulowice',
    'burzenin',
    'busko-zdrój',
    'bychawa',
    'byczyna',
    'bydgoszcz',
    'bystra',
    'bystrzyca',
    'bystrzyca kłodzka',
    'bytnica',
    'bytom',
    'bytom odrzański',
    'bytoń',
    'bytów',
    'cedry wielkie',
    'cedynia',
    'cegłów',
    'cekcyn',
    'celestynów',
    'ceranów',
    'cerkwica',
    'cewice',
    'chałupki',
    'chąśno',
    'chełm',
    'chełm county',
    'chełm śląski',
    'chełmek',
    'chełmiec',
    'chełmno',
    'chełmża',
    'chęciny',
    'chlastawa',
    'chlewiska',
    'chłapowo',
    'chmielnik',
    'chmielno',
    'chmielowice',
    'choceń',
    'chocianowice',
    'chocianów',
    'chociwel',
    'chocz',
    'choczewo',
    'chocznia',
    'chodecz',
    'chodel',
    'chodów',
    'chodzież',
    'chojna',
    'chojnice',
    'chojnów',
    'chomęciska duże',
    'chorkówka',
    'choroń',
    'choroszcz',
    'chorzele',
    'chorzów',
    'choszczno',
    'chotcza',
    'chrostkowo',
    'chrościna',
    'chróścice',
    'chróścina',
    'chruszczobród',
    'chrzanów',
    'chrzanów duży',
    'chrząstowice',
    'chrzypsko wielkie',
    'chwalęcice',
    'chwałowice',
    'chwaszczyno',
    'chybie',
    'chynów',
    'chyżne',
    'ciasna',
    'cichorajka',
    'ciechanowiec',
    'ciechanów',
    'ciechocin',
    'ciechocinek',
    'ciechocino',
    'ciechów',
    'cielądz',
    'cielmice',
    'ciepielów',
    'cieplice śląskie zdrój',
    'ciepłowody',
    'cieszanów',
    'cieszków',
    'cieszyn',
    'cięcina',
    'ciężkowice',
    'cisek',
    'cisiec',
    'cisna',
    'cisownica',
    'cmentarz centralny',
    'cmolas',
    'cybinka',
    'cyców',
    'cynków',
    'czajków',
    'czaniec',
    'czaplinek',
    'czapury',
    'czarków',
    'czarna',
    'czarna białostocka',
    'czarna dąbrówka',
    'czarna góra',
    'czarna woda',
    'czarne',
    'czarnia',
    'czarnków',
    'czarnochowice',
    'czarnocin',
    'czarnowąsy',
    'czarnożyły',
    'czarny bór',
    'czarny dunajec',
    'czastary',
    'czaszyn',
    'czchów',
    'czechowice-dziedzice',
    'czechy',
    'czeladź',
    'czemierniki',
    'czempiń',
    'czeremcha',
    'czermin',
    'czermna',
    'czernica',
    'czernice borowe',
    'czernichów',
    'czerniejewo',
    'czerniewice',
    'czernikowo',
    'czersk',
    'czerwieńsk',
    'czerwin',
    'czerwińsk nad wisłą',
    'czerwionka-leszczyny',
    'czerwonak',
    'czerwonka',
    'częstochowa',
    'człopa',
    'człuchów',
    'czudec',
    'czułów',
    'czyżew',
    'czyżkówko',
    'czyżowice',
    'ćmielów',
    'dalachów',
    'daleszyce',
    'dalików',
    'damasławek',
    'damnica',
    'darłowo',
    'daszewice',
    'daszyna',
    'dąbie',
    'dąbie dolne',
    'dąbrowa',
    'dąbrowa białostocka',
    'dąbrowa chełmińska',
    'dąbrowa górnicza',
    'dąbrowa tarnowska',
    'dąbrowa zielona',
    'dąbrowice',
    'dąbrówka',
    'dąbrówka starzeńska',
    'dąbrówno',
    'debrzno',
    'deszczno',
    'dębe wielkie',
    'dębica',
    'dębiec',
    'dęblin',
    'dębnica kaszubska',
    'dębno',
    'dębowa kłoda',
    'dębowa łąka',
    'dębowiec',
    'dębów',
    'długie',
    'długołęka',
    'długomiłowice',
    'długosiodło',
    'dłutów',
    'dmosin',
    'dobczyce',
    'dobiegniew',
    'dobieszowice',
    'dobra',
    'dobre',
    'dobre miasto',
    'dobrodzień',
    'dobroń',
    'dobroszyce',
    'dobrzany',
    'dobrzeń wielki',
    'dobrzyca',
    'dobrzyniewo duże',
    'dobrzyń nad wisłą',
    'dolice',
    'dolsk',
    'dołhobyczów',
    'domanice',
    'domaniewice',
    'domaradz',
    'domaszowice',
    'dominowo',
    'dopiewo',
    'dorohusk',
    'doruchów',
    'drawno',
    'drawsko',
    'drawsko pomorskie',
    'drelów',
    'drezdenko',
    'drobin',
    'drogomyśl',
    'drohiczyn',
    'drużbice',
    'drzewica',
    'drzewina',
    'drzycim',
    'dubiecko',
    'dubienka',
    'duczki',
    'dukla',
    'duszniki',
    'duszniki-zdrój',
    'dwikozy',
    'dworzysko',
    'dybków',
    'dydnia',
    'dygowo',
    'dymitrów duży',
    'dynów',
    'dywity',
    'dziadkowice',
    'dziadowa kłoda',
    'działdowo',
    'działoszyce',
    'działoszyn',
    'dziećmorowice',
    'dziekanów leśny',
    'dziemiany',
    'dziergowice',
    'dzierzążnia',
    'dzierzgoń',
    'dzierzgowo',
    'dzierzkowice',
    'dzierżoniów',
    'dziewin',
    'dzięgielów',
    'dzikowiec',
    'dzików stary',
    'dziwnów',
    'dzwola',
    'dźwierzuty',
    'elbląg',
    'ełk',
    'fabianki',
    'fajsławice',
    'fałków',
    'filipowice',
    'filipów',
    'firlej',
    'firoga',
    'fordon',
    'fosowskie',
    'frampol',
    'frank',
    'fredropol',
    'frombork',
    'frydek',
    'frydman',
    'frydrychowice',
    'frysztak',
    'gać',
    'gajewo',
    'galewice',
    'gałachy',
    'gałków mały',
    'garbatka-letnisko',
    'garbów',
    'garcz',
    'gardawice',
    'gardeja',
    'garwolin',
    'gaszowice',
    'gaworzyce',
    'gąbin',
    'gąsawa',
    'gąsocin',
    'gdańsk',
    'gdów',
    'gdynia',
    'gidle',
    'giebułtów',
    'giedlarowa',
    'gielniów',
    'gierałtowice',
    'gierłoż',
    'gierzwałd',
    'gietrzwałd',
    'gilowice',
    'gizałki',
    'giżycko',
    'glemieniec',
    'glinica',
    'glinka',
    'glinojeck',
    'gliwice',
    'głogoczów',
    'głogów',
    'głogów małopolski',
    'głogówek',
    'głowno',
    'główczyce',
    'główna',
    'głubczyce',
    'głuchołazy',
    'głuchów',
    'głuszyca',
    'głuszyca górna',
    'gniazdów',
    'gniechowice',
    'gniew',
    'gniewino',
    'gniewkowo',
    'gniezno',
    'gnieżdżewo',
    'gnojnik',
    'gnojno',
    'goczałkowice zdrój',
    'godów',
    'godzianów',
    'godziszewy',
    'godziszka',
    'godziszów',
    'godziszów pierwszy',
    'gogolin',
    'golcowa',
    'golczewo',
    'goleniów',
    'goleszów',
    'golina',
    'golub-dobrzyń',
    'gołańcz',
    'gołąbki',
    'gołdap',
    'gołkowice',
    'gołuchów',
    'gołymin-ośrodek',
    'gomunice',
    'goniadz',
    'goraj',
    'gorenice',
    'gorlice',
    'gorliczyna',
    'gorzkowice',
    'gorzków',
    'gorzów śląski',
    'gorzów wielkopolski',
    'gorzyce',
    'gorzyce wielkie',
    'gorzyczki',
    'gorzyniec',
    'gostkowo',
    'gostycyn',
    'gostynin',
    'gostyń',
    'goszczanów',
    'goszczyn',
    'gościcino',
    'gościeradów',
    'gościno',
    'goślinki',
    'gowarczów',
    'goworowo',
    'gozdnica',
    'gozdowo',
    'gozdów',
    'góra',
    'góra kalwaria',
    'góra ropczycka',
    'góra świętej małgorzaty',
    'górażdże',
    'górki',
    'górki wielkie',
    'górniki',
    'górno',
    'górowo iławeckie',
    'górzno',
    'górzyca',
    'gózd',
    'grabica',
    'grabowiec',
    'grabownica starzeńska',
    'grabowo kościerskie',
    'grabów',
    'grabów nad prosną',
    'grabów rycki',
    'grajewo',
    'granica',
    'granowo',
    'grębków',
    'grębocice',
    'gręboszów',
    'grębów',
    'grodków',
    'grodziec',
    'grodzisk mazowiecki',
    'grodzisk wielkopolski',
    'grodzisko dolne',
    'grodzisko górne',
    'grojec',
    'gromada',
    'gromadka',
    'gromnik',
    'gronowo elbląskie',
    'gronowo górne',
    'gródków',
    'grójec',
    'grudki',
    'grudusk',
    'grudziądz',
    'grunwald',
    'gruszów wielki',
    'gruta',
    'grybów',
    'gryfice',
    'gryfino',
    'gryfów śląski',
    'grzechynia',
    'grzegorzew',
    'grzegorzówka',
    'grzęska',
    'grzmiąca',
    'grzybowa góra',
    'grzybowo',
    'gubin',
    'gutwin',
    'guzów',
    'gwoźnica górna',
    'gzy',
    'haczów',
    'hajnówka',
    'halinów',
    'hallerowo',
    'handzlówka',
    'hańsk',
    'harasiuki',
    'harbutowice',
    'hażlach',
    'hel',
    'helenówka',
    'henryków',
    'herby',
    'hornówek',
    'horodło',
    'horyniec-zdrój',
    'hrubieszów',
    'hucisko',
    'humniska',
    'husów',
    'huta stara b',
    'hyżne',
    'iława',
    'iłowa',
    'iłowo -osada',
    'iłów',
    'iłża',
    'imielin',
    'imielno',
    'inowłódz',
    'inowrocław',
    'inwałd',
    'ińsko',
    'istebna',
    'iwaniska',
    'iwanowice',
    'iwierzyce',
    'iwkowa',
    'iwonicz-zdrój',
    'izabelin',
    'izbica',
    'izbica kujawska',
    'izbicko',
    'izdebnik',
    'jabłonica polska',
    'jabłonka',
    'jabłonna',
    'jabłonna lacka',
    'jabłonowo pomorskie',
    'jabłoń',
    'jadowniki',
    'jadowniki mokre',
    'jadów',
    'jagiełła',
    'jakubowice murowane',
    'jakubów',
    'janikowo',
    'jankowice',
    'jankowice rybnickie',
    'janków przygodzki',
    'janowice',
    'janowice wielkie',
    'janowiec',
    'janowiec wielkopolski',
    'janów',
    'janów lubelski',
    'janów podlaski',
    'januszkowice',
    'jaraczewo',
    'jarczów',
    'jarocin',
    'jarosław',
    'jaroszowice',
    'jasienica',
    'jasienica rosielna',
    'jasieniec',
    'jasień',
    'jasionów',
    'jasło',
    'jastarnia',
    'jastków',
    'jastrowie',
    'jastrząb',
    'jastrzębia',
    'jastrzębia góra',
    'jastrzębie',
    'jastrzębie dolne',
    'jastrzębie zdrój',
    'jastrzębie-zdrój',
    'jaśliska',
    'jawor',
    'jawornik',
    'jawornik polski',
    'jaworze',
    'jaworzno',
    'jaworzyna śląska',
    'jaworzynka',
    'jedlicze',
    'jedlina-zdrój',
    'jedlińsk',
    'jedlnia-letnisko',
    'jednorożec',
    'jedwabne',
    'jedwabno',
    'jejkowice',
    'jelcz',
    'jelcz laskowice',
    'jelcz-laskowice',
    'jelenia góra',
    'jeleśnia',
    'jemielnica',
    'jemielno',
    'jenin',
    'jerzmanowice',
    'jeziora wielkie',
    'jeziorany',
    'jeziorna oborska',
    'jeziorzany',
    'jeżewo',
    'jeżowe',
    'jeżów',
    'jeżów sudecki',
    'jeżyce',
    'jędrzejów',
    'jodłowa',
    'jodłówka',
    'jodłówka-wałki',
    'joniec',
    'jonkowo',
    'jordanów',
    'jordanów śląski',
    'józefosław',
    'józefowiec',
    'józefów',
    'józefów nad wisłą',
    'juchnowiec dolny',
    'juchnowiec kościelny',
    'jugów',
    'julianów',
    'juszczyn',
    'juszczyna',
    'jutrosin',
    'kabaty',
    'kaczory',
    'kaczyce',
    'kadzidło',
    'kalej',
    'kalety',
    'kaliska',
    'kalisz',
    'kalisz pomorski',
    'kalwaria zebrzydowska',
    'kałuszyn',
    'kamesznica',
    'kamienica',
    'kamienica polska',
    'kamieniec',
    'kamieniec wrocławski',
    'kamieniec ząbkowicki',
    'kamienna góra',
    'kamiennik',
    'kamień',
    'kamień krajeński',
    'kamień pomorski',
    'kamieńsk',
    'kamionka',
    'kamionka wielka',
    'kampinos',
    'kamyk',
    'kaniów',
    'kańczuga',
    'karczew',
    'karczmiska',
    'kargowa',
    'karlino',
    'karnice',
    'karniewo',
    'karniszyn',
    'karpacz',
    'karsin',
    'kartuzy',
    'kasina wielka',
    'kaszczor',
    'kaszów',
    'katowice',
    'kawęczyn',
    'kawęczyn nowy',
    'kazanów',
    'kazimierz biskupi',
    'kazimierz dolny',
    'kazimierza wielka',
    'kaźmierz',
    'kąkolewo',
    'kąty wrocławskie',
    'kcynia',
    'kędzierzyn-koźle',
    'kępa gostecka',
    'kępice',
    'kępie żaleszańskie',
    'kępno',
    'kęsowo',
    'kęszyn',
    'kętrzyn',
    'kęty',
    'kielanówka',
    'kielce',
    'kiełczów',
    'kiełpin',
    'kiernozia',
    'kietrz',
    'kije',
    'kikół',
    'kisielice',
    'kiszkowo',
    'klecza dolna',
    'kleczew',
    'klembów',
    'klenica',
    'kleszczele',
    'kleszczewo',
    'kleszczów',
    'klęczany',
    'klikuszowa',
    'klimontów',
    'klonowa',
    'kluczbork',
    'klucze',
    'kluki',
    'kluszkowce',
    'klwów',
    'kłaj',
    'kłecko',
    'kłobuck',
    'kłoczew',
    'kłoda',
    'kłodawa',
    'kłodzko',
    'kłomnice',
    'knurów',
    'knyszyn',
    'kobiernice',
    'kobierzyce',
    'kobiór',
    'kobyla góra',
    'kobylanka',
    'kobylin',
    'kobylnica',
    'kobyłka',
    'kochanowice',
    'kocierzew południowy',
    'kock',
    'koczała',
    'kodeń',
    'kodrąb',
    'kokotów',
    'kolbudy',
    'kolbuszowa',
    'kolbuszowa dolna',
    'koleczkowo',
    'kolno',
    'kolonia wolwinów',
    'kolonowskie',
    'kolsko',
    'koluszki',
    'kołaczkowo',
    'kołaczyce',
    'kołbaskowo',
    'kołbiel',
    'kołczygłowy',
    'koło',
    'kołobrzeg',
    'komańcza',
    'komarówka podlaska',
    'komarów-osada',
    'komorniki',
    'komorów',
    'komprachcice',
    'konary',
    'koniaków',
    'koniecpol',
    'konieczkowa',
    'konin',
    'konin county',
    'konopiska',
    'konotop',
    'konstancin-jeziorna',
    'konstantynów',
    'konstantynów łódzki',
    'kończyce',
    'kończyce małe',
    'kończyce wielkie',
    'końskie',
    'końskowola',
    'koprzywnica',
    'korbielów',
    'korczew',
    'korczyna',
    'korfantów',
    'kornowac',
    'koronowo',
    'korsze',
    'korycin',
    'korytnica',
    'korzenna',
    'kosakowo',
    'kosina',
    'kosów lacki',
    'kostomłoty',
    'kostomłoty drugie',
    'kostomłoty pierwsze',
    'kostrzyn',
    'kostrzyn nad odrą',
    'koszalin',
    'koszarawa',
    'koszęcin',
    'koszutka',
    'koszyce',
    'koszyce wielkie',
    'kościan',
    'kościelec',
    'kościelisko',
    'kościerzyna',
    'kotla',
    'kotlin',
    'kotuń',
    'kowal',
    'kowala',
    'kowale',
    'kowale oleckie',
    'kowalewo',
    'kowalewo pomorskie',
    'kowary',
    'kowiesy',
    'koziegłowy',
    'kozielice',
    'kozienice',
    'kozłowa góra',
    'kozłowo',
    'kozłów',
    'kozłówka',
    'kozubszczyzna',
    'kozy',
    'koźle',
    'koźmin wielkopolski',
    'koźminek',
    'kożuchów',
    'kórnik',
    'kraczkowa',
    'krajenka',
    'kraków',
    'kramarzówka',
    'kramsk',
    'krapkowice',
    'krasiczyn',
    'krasne',
    'krasnobród',
    'krasnopol',
    'krasnosielc',
    'krasnystaw',
    'krasocin',
    'kraszewice',
    'kraśniczyn',
    'kraśnik',
    'krempna',
    'krobia',
    'kroczyce',
    'krokowa',
    'krosno',
    'krosno odrzańskie',
    'krościenko nad dunajcem',
    'krościenko wyżne',
    'krośnica',
    'krośnice',
    'krośniewice',
    'krotoszyce',
    'krotoszyn',
    'kruklanki',
    'krupski młyn',
    'kruszwica',
    'krynica morska',
    'krynica-wieś',
    'krynica-zdrój',
    'krynice',
    'krynki',
    'kryry',
    'kryspinów',
    'krzanowice',
    'krzczonów',
    'krzeczowice',
    'krzeczów',
    'krzemienica',
    'krzemieniewo',
    'krzepice',
    'krzepocinek',
    'krzeszowice',
    'krzeszów',
    'krzeszyce',
    'krzewina',
    'krzęcin',
    'krzykosy',
    'krzymów',
    'krzynowłoga mała',
    'krzyszkowice',
    'krzywaczka',
    'krzywcza',
    'krzywda',
    'krzywe',
    'krzywiń',
    'krzyż wielkopolski',
    'krzyżanowice',
    'krzyżanów',
    'krzyżowa',
    'krzyżowice',
    'krzyżowniki',
    'ksawerów',
    'książ wielkopolski',
    'książenice',
    'książki',
    'księżomierz',
    'księżpol',
    'kuchary',
    'kuczbork-osada',
    'kudowa-zdrój',
    'kuków',
    'kuligowo',
    'kunice',
    'kunice żarskie',
    'kunów',
    'kup',
    'kupienin',
    'kurozwęcz',
    'kurozwęki',
    'kurów',
    'kuryłówka',
    'kurzętnik',
    'kuślin',
    'kutno',
    'kuźnia raciborska',
    'kuźnica',
    'kwaczała',
    'kwiatkowice',
    'kwidzyn',
    'kwieciszewo',
    'kwilcz',
    'lachowice',
    'laliki',
    'lanckorona',
    'lasek',
    'laskowa',
    'laszki',
    'latowicz',
    'lądek',
    'lądek-zdrój',
    'lechuty',
    'lecka',
    'lednica niemiecka',
    'legionowo',
    'legnica',
    'legnickie pole',
    'lelkowo',
    'lelów',
    'leńcze',
    'lesko',
    'leszczyny',
    'leszno',
    'lesznowola',
    'leśna',
    'leśna podlaska',
    'leśnica',
    'lewin brzeski',
    'lewin kłodzki',
    'leżajsk',
    'lębork',
    'lędziny',
    'lgota wielka',
    'libertów',
    'libiąż',
    'libiąż mały',
    'licheń stary',
    'lidzbark',
    'lidzbark warmiński',
    'ligota',
    'likusy',
    'limanowa',
    'linia',
    'liniewo',
    'lipce reymontowskie',
    'lipiany',
    'lipie',
    'lipinki',
    'lipinki łużyckie',
    'lipka',
    'lipki',
    'lipnica',
    'lipnica mała',
    'lipnica wielka',
    'lipnik',
    'lipno',
    'lipowa',
    'lipowiec kościelny',
    'lipsk',
    'lipsko',
    'lipusz',
    'lisewo',
    'lisewo malborskie',
    'lisia góra',
    'lisków',
    'liszki',
    'liw',
    'lniano',
    'lubaczów',
    'lubanie',
    'lubań',
    'lubartów',
    'lubasz',
    'lubawa',
    'lubawka',
    'lubenia',
    'lubichowo',
    'lubicz dolny',
    'lubicz górny',
    'lubień',
    'lubień kujawski',
    'lubiewo',
    'lubin',
    'lubiszyn',
    'lublewo gdańskie',
    'lublin',
    'lubliniec',
    'lubniewice',
    'lubochnia',
    'lubomia',
    'lubomierz',
    'lubomino',
    'luboń',
    'lubowidz',
    'lubraniec',
    'lubrza',
    'lubsko',
    'lubsza',
    'lubycza królewska',
    'luchowo',
    'ludwikowice kłodzkie',
    'ludwikowo',
    'ludwin',
    'ludźmierz',
    'luszowice',
    'lutocin',
    'lutomiersk',
    'lutoryż',
    'lutowiska',
    'lututów',
    'luzino',
    'lwówek',
    'lwówek śląski',
    'lyski',
    'łabiszyn',
    'łabowa',
    'łabunie',
    'łagiewniki',
    'łagów',
    'łambinowice',
    'łanięta',
    'łany wielkie',
    'łańcut',
    'łapanów',
    'łapczyca',
    'łapiguz',
    'łapsze niżne',
    'łapy',
    'łapy zięciuki',
    'łasin',
    'łask',
    'łaskarzew',
    'łaszczów',
    'łasztownia',
    'ławica',
    'łaziska',
    'łaziska górne',
    'łazy',
    'łazy bledowskie',
    'łażany',
    'łąck',
    'łącko',
    'łączany',
    'łączki jagiellońskie',
    'łączna',
    'łąka prudnicka',
    'łeba',
    'łęczna',
    'łęczyca',
    'łęczyce',
    'łęgowo',
    'łęka opatowska',
    'łękawica',
    'łęki',
    'łęki dolne',
    'łęki górne',
    'łęki szlacheckie',
    'łęknica',
    'łęknice',
    'łętownia',
    'łobez',
    'łobodno',
    'łobżenica',
    'łochów',
    'łodygowice',
    'łoje',
    'łomazy',
    'łomianki',
    'łomianki dolne',
    'łomża',
    'łomża county',
    'łomżyca',
    'łoniów',
    'łopiennik górny',
    'łopuszka wielka',
    'łopuszna',
    'łopuszno',
    'łosice',
    'łosiów',
    'łososina dolna',
    'łowicz',
    'łódź',
    'łubianka',
    'łubniany',
    'łubnice',
    'łubowo',
    'łukowa',
    'łukowica',
    'łuków',
    'łużna',
    'łyse',
    'łysica',
    'łysomice',
    'łyszkowice',
    'maciejowice',
    'majdan królewski',
    'maków',
    'maków mazowiecki',
    'maków podhalański',
    'malanów',
    'malbork',
    'malczyce',
    'malec',
    'mała wieś',
    'małdyty',
    'małkinia górna',
    'małogoszcz',
    'małomice',
    'mały płock',
    'manasterz',
    'maniowy',
    'marciszów',
    'marciszów górny',
    'mareza',
    'margonin',
    'marianowo',
    'marki',
    'markłowice',
    'markowa',
    'markuszów',
    'marszewo',
    'marwice',
    'marymont',
    'masłów',
    'maszewo',
    'maszewo duże',
    'maszkienice',
    'matówka',
    'mazańcowice',
    'medyka',
    'mełgiew',
    'mędrzechów',
    'mętków',
    'miasteczko krajeńskie',
    'miasteczko śląskie',
    'miastko',
    'miastków kościelny',
    'miączyn',
    'michalinów',
    'michałowice',
    'michałowo',
    'michałów',
    'michałów-reginów',
    'michów',
    'miechów',
    'miechów charsznica',
    'miedziana góra',
    'miedzichowo',
    'miedzna',
    'miedzno',
    'miedźna',
    'miejsce piastowe',
    'miejska górka',
    'mielec',
    'mieleszyn',
    'mielno',
    'mieroszów',
    'mierzęcice',
    'mieszkowice',
    'mieścisko',
    'międzybórz',
    'międzybrodzie bialskie',
    'międzychód',
    'międzygórze',
    'międzylesie',
    'międzyrzec podlaski',
    'międzyrzecz',
    'międzyrzecze górne',
    'międzyzdroje',
    'miękinia',
    'miętne',
    'mikołajki',
    'mikołajki pomorskie',
    'mikołów',
    'mikstat',
    'mikułowice',
    'milanów',
    'milanówek',
    'milejczyce',
    'milejów',
    'milicz',
    'milówka',
    'miłakowo',
    'miłkowice',
    'miłków',
    'miłomłyn',
    'miłoradz',
    'miłosław',
    'miłostów',
    'minkowice',
    'mińsk mazowiecki',
    'mircze',
    'mirków',
    'mirocin',
    'mirosławiec',
    'mirów',
    'mirsk',
    'mirzec',
    'mława',
    'młodzieszyn',
    'młynary',
    'młynarze',
    'młyny',
    'mnich',
    'mników',
    'mniów',
    'mniszków',
    'mochowo',
    'modliborzyce',
    'modlnica',
    'modlniczka',
    'modrzejów',
    'mogielnica',
    'mogilany',
    'mogilno',
    'mojcza',
    'mokas',
    'mokobody',
    'mokrsko',
    'mońki',
    'morawica',
    'morawsko',
    'morąg',
    'mordy',
    'morgowniki',
    'moryń',
    'mosina',
    'mosty',
    'moszczanka',
    'moszczenica',
    'mrągowo',
    'mrocza',
    'mrozów',
    'mrozy',
    'mrzezino',
    'mrzeżyno',
    'mstów',
    'mszana',
    'mszana dolna',
    'mszana górna',
    'mszczonów',
    'muranów',
    'murcki',
    'murowana goślina',
    'murów',
    'muszyna',
    'mykanów',
    'mysiadło',
    'mysłakowice',
    'mysłowice',
    'myszków',
    'myszyniec',
    'myślachowice',
    'myślenice',
    'myślibórz',
    'nadarzyn',
    'nagłowice',
    'nakło',
    'nakło nad notecią',
    'nałęczów',
    'namysłów',
    'naprawa',
    'narew',
    'narol',
    'naruszewo',
    'nasielsk',
    'nawojowa',
    'nekla',
    'nędza',
    'nidek',
    'nidzica',
    'niebieszczany',
    'niebocko',
    'nieborów',
    'niebylec',
    'niechanowo',
    'niechobrz',
    'niedobczyce',
    'niedomice',
    'niedrzwica duża',
    'niedzica',
    'niedźwiada',
    'niedźwiedź',
    'niegowonice',
    'nielisz',
    'niemce',
    'niemcza',
    'niemodlin',
    'nienadowa',
    'niepołomice',
    'nieporęt',
    'nieszawa',
    'nisko',
    'niwiska',
    'nowa dęba',
    'nowa góra',
    'nowa ruda',
    'nowa sarzyna',
    'nowa słupia',
    'nowa sól',
    'nowa studnica',
    'nowa wieś',
    'nowa wieś lęborska',
    'nowa wieś wielka',
    'nowe',
    'nowe brzesko',
    'nowe grocholice',
    'nowe kozłowice',
    'nowe lipiny',
    'nowe miasteczko',
    'nowe miasto',
    'nowe miasto lubawskie',
    'nowe miasto nad pilicą',
    'nowe miasto nad wartą',
    'nowe ostrowy',
    'nowe sioło',
    'nowe skalmierzyce',
    'nowe warpno',
    'nowodwór',
    'nowogard',
    'nowogrodziec',
    'nowogród',
    'nowogród bobrzański',
    'nowogródek pomorski',
    'nowosielce',
    'nowosielce-gniewosz',
    'nowosolna',
    'nowy duninów',
    'nowy dwór gdański',
    'nowy dwór mazowiecki',
    'nowy korczyn',
    'nowy łuków',
    'nowy sącz',
    'nowy staw',
    'nowy świat',
    'nowy targ',
    'nowy tomyśl',
    'nowy wielisław',
    'nowy wiśnicz',
    'nowy żmigród',
    'nozdrzec',
    'nur',
    'nurzec-stacja',
    'nysa',
    'oborniki',
    'oborniki śląskie',
    'obozisko',
    'obrazów',
    'obrowo',
    'obryte',
    'obrzycko',
    'obsza',
    'ochaby',
    'ochla',
    'ochocice',
    'ochojno',
    'ochotnica dolna',
    'odolanów',
    'odrzykoń',
    'odrzywół',
    'ogorzelnik',
    'ogrodzieniec',
    'ojrzeń',
    'okocim',
    'okonek',
    'okrajnik',
    'oksa',
    'olchowce',
    'olecko',
    'olesno',
    'oleszyce',
    'oleśnica',
    'olkusz',
    'olszana',
    'olszanica',
    'olszanka',
    'olszówka',
    'olsztyn',
    'olsztynek',
    'olszyna',
    'olza',
    'oława',
    'ołpiny',
    'opalenica',
    'opatowiec',
    'opatów',
    'opatówek',
    'opinogóra górna',
    'opoczno',
    'opole',
    'opole lubelskie',
    'oporów',
    'orchowo',
    'orla',
    'orle',
    'orły',
    'orneta',
    'ornontowice',
    'orońsko',
    'orzech',
    'orzechówka',
    'orzepowice',
    'orzesze',
    'orzysz',
    'osie',
    'osieck',
    'osieczany',
    'osieczna',
    'osiedle-nowiny',
    'osiek',
    'osiek jasielski',
    'osiek mały',
    'osiek nad notecią',
    'osielec',
    'osielsko',
    'osięciny',
    'osina',
    'osjaków',
    'osowa góra',
    'ostaszewo',
    'ostoja',
    'ostrężnica',
    'ostrołęka',
    'ostroróg',
    'ostroszowice',
    'ostrowiec świętokrzyski',
    'ostrowite',
    'ostrowsko',
    'ostrowy',
    'ostrowy nad okszą',
    'ostróda',
    'ostrów',
    'ostrów lubelski',
    'ostrów mazowiecka',
    'ostrów wielkopolski',
    'ostrówek',
    'ostrzeszów',
    'ośno lubuskie',
    'oświęcim',
    'otmęt',
    'otmuchów',
    'otrębusy',
    'otwock',
    'otyń',
    'ouszniki',
    'owczarnia',
    'ozimek',
    'ozorków',
    'ożarowice',
    'ożarów',
    'ożarów mazowiecki',
    'pabianice',
    'pacanów',
    'pacyna',
    'paczków',
    'padew narodowa',
    'pajęczno',
    'pakosław',
    'pakosławice',
    'pakość',
    'palcza',
    'pamiątkowo',
    'paniówki',
    'panki',
    'pantalowice',
    'paprotnia',
    'paradyż',
    'parchowo',
    'parczew',
    'parysów',
    'parzęczew',
    'pasieczki',
    'pasłęk',
    'pasym',
    'paszowice',
    'pawlikowice',
    'pawłosiów',
    'pawłowice',
    'pawłowiczki',
    'pawłów',
    'pawonków',
    'pątnów',
    'pcim',
    'pecna',
    'pelplin',
    'pełczyce',
    'perlejewo',
    'perzów',
    'pewel ślemieńska',
    'pewel wielka',
    'pęczniew',
    'pępowo',
    'piaseczno',
    'piasek',
    'piaski',
    'piaskowice',
    'piastów',
    'piątek',
    'piątnica',
    'piechowice',
    'piecki',
    'piekary',
    'piekary śląskie',
    'piekielnik',
    'piekoszów',
    'pielgrzymowice',
    'pieniężno',
    'pieńsk',
    'piersk',
    'pierściec',
    'pierzchnica',
    'pieszyce',
    'pietrowice wielkie',
    'pietrzykowice',
    'pilawa',
    'pilchowice',
    'pile',
    'pilica',
    'pilzno',
    'piła',
    'piława',
    'piława górna',
    'pińczów',
    'pionki',
    'piotrków kujawski',
    'piotrków trybunalski',
    'pisarzowice',
    'piskorowice',
    'pisz',
    'piszczac',
    'piwniczna-zdrój',
    'pleszew',
    'pleśna',
    'plewiska',
    'pławno',
    'pławo',
    'płaza',
    'płock',
    'płoniawy-bramura',
    'płońsk',
    'płoty',
    'płużnica',
    'pniewy',
    'poberezany',
    'pobiedziska',
    'pobierowo',
    'pobitno',
    'poddębice',
    'podebłocie',
    'podedwórze',
    'podegrodzie',
    'podemłynek',
    'podgórzyn',
    'podgrodzie',
    'podklasztorze',
    'podkowa leśna',
    'podłęże',
    'podwilk',
    'pogorzela',
    'pogorzyce',
    'pogórska wola',
    'pogórze',
    'pogrzebień',
    'pogwizdów',
    'pokój',
    'pokrówka',
    'pokrzywnica',
    'polaki',
    'polanica-zdrój',
    'polanka wielka',
    'polanów',
    'polańczyk',
    'police',
    'policzna',
    'polkowice',
    'polska cerekiew',
    'połajewo',
    'połaniec',
    'połczyn-zdrój',
    'połomia',
    'pomiechówek',
    'pomorzany',
    'poniatowa',
    'poniec',
    'ponikiew',
    'popielów',
    'popów',
    'poraj',
    'poraż',
    'porąbka',
    'porąbka uszewska',
    'poręba',
    'poręba spytkowska',
    'poręba wielka',
    'poronin',
    'posada dolna',
    'posejny',
    'poświętne',
    'potęgowo',
    'potok górny',
    'potok wielki',
    'potok złoty',
    'potworów',
    'powidz',
    'pozezdrze',
    'poznań',
    'prabuty',
    'pracze odrzańskie',
    'praszka',
    'prażmów',
    'prądnik czerwony',
    'prochowice',
    'promna',
    'prostki',
    'proszowice',
    'prószków',
    'pruchna',
    'pruchnik',
    'prudnik',
    'prusice',
    'prusinowice',
    'pruska plebanka',
    'pruszcz',
    'pruszcz gdański',
    'pruszków',
    'przasnysz',
    'przechlewo',
    'przecieszyn',
    'przeciszów',
    'przecław',
    'przedbórz',
    'przedecz',
    'przedmieście dubieckie',
    'przeginia',
    'przelewice',
    'przemęt',
    'przemków',
    'przemyśl',
    'przesmyki',
    'przeworno',
    'przeworsk',
    'przewóz',
    'przędzel',
    'przodkowo',
    'przybiernów',
    'przyborów',
    'przybyszówka',
    'przygodzice',
    'przykona',
    'przyłęk',
    'przyrów',
    'przysłop',
    'przystajń',
    'przysucha',
    'przyszowice',
    'przytkowice',
    'przytoczna',
    'przytoczno',
    'przytyk',
    'przywidz',
    'psary',
    'pszczew',
    'pszczółki',
    'pszczyna',
    'pszów',
    'puchaczów',
    'puck',
    'puławy',
    'pułtusk',
    'puńców',
    'puńsk',
    'purda',
    'puszcza mariańska',
    'puszczykowo',
    'pyrzowice',
    'pyrzyce',
    'pyskowice',
    'pysznica',
    'pyzdry',
    'raba wyżna',
    'rabka-zdrój',
    'rachanie',
    'raciąż',
    'raciążek',
    'racibórz',
    'racławice',
    'racławice śląskie',
    'raczki',
    'radecznica',
    'radgoszcz',
    'radków',
    'radlikowiec',
    'radlin',
    'radłów',
    'radocza',
    'radom',
    'radom county',
    'radomin',
    'radomsko',
    'radomyśl',
    'radomyśl wielki',
    'radostowice',
    'radoszyce',
    'radowo małe',
    'radwanice',
    'radymno',
    'radzanowo',
    'radzanów',
    'radziechowy',
    'radziejowice',
    'radziejów',
    'radziłów',
    'radzionków',
    'radziszów',
    'radzymin',
    'radzyń chełmiński',
    'radzyń podlaski',
    'rajcza',
    'rajgród',
    'rajsko',
    'rakoniewice',
    'raków',
    'rakszawa',
    'raniżów',
    'raszczyce',
    'raszków',
    'raszowa',
    'raszyn',
    'ratowice',
    'rawa mazowiecka',
    'rawicz',
    'rąbino',
    'rączna',
    'recz',
    'reda',
    'redzikowo',
    'regimin',
    'regnów',
    'regulice',
    'rejowiec',
    'rejowiec fabryczny',
    'rekowo dolne',
    'reńska wieś',
    'repki',
    'republic of poland',
    'resko',
    'reszel',
    'rewal',
    'ręczno',
    'rędziny',
    'roczyny',
    'rogalinek',
    'rogalów',
    'rogowo',
    'rogoźnik',
    'rogoźno',
    'rogów',
    'rogóźno',
    'rokiciny',
    'rokiciny-kolonia',
    'rokietnica',
    'rokitnica',
    'rokitno',
    'rokitno szlacheckie',
    'ropa',
    'ropczyce',
    'rososz',
    'rossosz',
    'rościszewo',
    'rotmanka',
    'rozbórz',
    'rozdrażew',
    'rozogi',
    'rozprza',
    'rozwadza',
    'roźwienica',
    'rożental',
    'rożwienica',
    'różan',
    'ruciane-nida',
    'ruda',
    'ruda maleniecka',
    'ruda śląska',
    'ruda-huta',
    'rudawa',
    'rudka',
    'rudna',
    'rudna mała',
    'rudna wielka',
    'rudnik',
    'rudnik nad sanem',
    'rudniki',
    'rudy',
    'rudziczka',
    'rudziniec',
    'rumia',
    'rumunki lipnowskie',
    'rury jezuickie',
    'rusiec',
    'rusinów',
    'rusocice',
    'rutki',
    'rutki-kossaki',
    'rybarzowice',
    'rybczewice',
    'rybie',
    'rybna',
    'rybnik',
    'rybno',
    'rycerka dolna',
    'rycerka górna',
    'rychtal',
    'rychwał',
    'ryczów',
    'ryczywół',
    'rydułtowy',
    'rydzyna',
    'ryglice',
    'ryjewo',
    'ryki',
    'rymanów',
    'rymań',
    'ryn',
    'rypin',
    'rytro',
    'rytwiany',
    'rząska',
    'rząśnik',
    'rzeczenica',
    'rzeczniów',
    'rzeczyca',
    'rzekuń',
    'rzepedź',
    'rzepiennik strzyżewski',
    'rzepin',
    'rzeszotary',
    'rzeszów',
    'rzewnie',
    'rzezawa',
    'rzgów',
    'rzgów pierwszy',
    'rzozów',
    'rzyki',
    'sabnie',
    'sadki',
    'sadkowice',
    'sadlinki',
    'sadowie',
    'sadowne',
    'samborzec',
    'sandomierz',
    'sanka',
    'sanniki',
    'sanok',
    'santok',
    'sarnaki',
    'sarnikierz',
    'sarnowice',
    'sarnów',
    'sarnówka',
    'sawin',
    'sączów',
    'sąspów',
    'secemin',
    'sejny',
    'serniki',
    'serock',
    'serokomla',
    'sędziejowice',
    'sędziszów',
    'sędziszów małopolski',
    'sękowa',
    'sępopol',
    'sępólno krajeńskie',
    'sianów',
    'sicienko',
    'sidzina',
    'siechnice',
    'siedlce',
    'siedlec',
    'siedleczka',
    'siedliska',
    'siedlisko',
    'siekierczyn',
    'siemianowice śląskie',
    'siemiatycze',
    'siemiątkowo',
    'siemiechów',
    'siemień',
    'siemkowice',
    'sieniawa',
    'sieniawa żarska',
    'siennica',
    'siennica różana',
    'sienno',
    'siepraw',
    'sieradz',
    'sieradza',
    'sierakowice',
    'sieraków',
    'sieraków śląski',
    'sieroszewice',
    'sierpc',
    'sierzchów',
    'sietesz',
    'siewierz',
    'siołkowa',
    'sitno',
    'siwki',
    'skalbmierz',
    'skalmierzyce',
    'skała',
    'skarbimierz',
    'skarbimierz osiedle',
    'skarszewy',
    'skaryszew',
    'skarżysko kościelne',
    'skarżysko-kamienna',
    'skaszewo',
    'skawica',
    'skawina',
    'skawinki',
    'skąpe',
    'skępe',
    'skierbieszów',
    'skierniewice',
    'skoczów',
    'skoki',
    'skołyszyn',
    'skomielna czarna',
    'skomlin',
    'skopanie',
    'skorogoszcz',
    'skoroszyce',
    'skorupy',
    'skotnica',
    'skórcz',
    'skórka',
    'skórzec',
    'skrwilno',
    'skrzydlna',
    'skrzynówek',
    'skrzyszów',
    'skulsk',
    'skwierzyna',
    'sława',
    'sławatycze',
    'sławek',
    'sławęcin',
    'sławięcice',
    'sławków',
    'sławno',
    'sławoborze',
    'słomniki',
    'słońsk',
    'słopnice',
    'słotowa',
    'słotwiny',
    'słubice',
    'słup',
    'słupca',
    'słupia',
    'słupia pod kępnem',
    'słupiec',
    'słupno',
    'słupsk',
    'smęgorzów',
    'smętowo graniczne',
    'smolec',
    'smołdzino',
    'smyków',
    'sobienie jeziory',
    'sobków',
    'sobolew',
    'sobótka',
    'sochaczew',
    'sochocin',
    'sokolniki',
    'sokołów górny',
    'sokołów małopolski',
    'sokołów podlaski',
    'sokoły',
    'sokółka',
    'solec kujawski',
    'solec nad wisłą',
    'solec-zdrój',
    'somianka',
    'somonino',
    'sompolno',
    'sonina',
    'sońsk',
    'sopot',
    'sopotnia wielka',
    'sosnowica',
    'sosnowice',
    'sosnowiec',
    'sosnówka',
    'sośnica',
    'sośnicowice',
    'sośnie',
    'sośno',
    'sól',
    'spiczyn',
    'sporysz',
    'spytkowice',
    'srokowo',
    'stalowa wola',
    'stanisław dolny',
    'stanisław górny',
    'stanisławice',
    'stanisławów',
    'stanisławów pierwszy',
    'stanowice',
    'stara biała',
    'stara błotnica',
    'stara dąbrowa',
    'stara kamienica',
    'stara kiszewa',
    'stara kornica',
    'stara wieś',
    'starachowice',
    'starcza',
    'stare babice',
    'stare bogaczowice',
    'stare czarnowo',
    'stare juchy',
    'stare kurowo',
    'stare miasto',
    'stare pole',
    'stare stawy',
    'stargard',
    'starogard gdański',
    'starokrzepice',
    'starosielce',
    'starowa góra',
    'staroźreby',
    'stary sącz',
    'stary targ',
    'stary wiśnicz',
    'stary zamość',
    'staszów',
    'stawiguda',
    'stawiski',
    'stawiszyn',
    'stąporków',
    'steblewo',
    'stefanów',
    'stegna',
    'stepnica',
    'sterdyń',
    'stęszew',
    'stężyca',
    'stoczek',
    'stoczek łukowski',
    'stopnica',
    'stoszowice',
    'strachocina',
    'strachowice',
    'strachówka',
    'straszydle',
    'straszyn',
    'strawczyn',
    'stromiec',
    'stronie',
    'stronie śląskie',
    'stróża',
    'strumień',
    'stryków',
    'stryszawa',
    'stryszów',
    'strzałkowo',
    'strzebiń',
    'strzegom',
    'strzegowo',
    'strzelce',
    'strzelce krajeńskie',
    'strzelce opolskie',
    'strzelce wielkie',
    'strzeleczki',
    'strzelin',
    'strzelno',
    'strzyżowice',
    'strzyżów',
    'stubno',
    'studzienice',
    'studzionka',
    'stupsk',
    'subkowy',
    'sucha',
    'sucha beskidzka',
    'suchań',
    'suchedniów',
    'suchowola',
    'suchożebry',
    'suchy dąb',
    'suchy las',
    'sulbiny górne',
    'sulechów',
    'sulejów',
    'sulejówek',
    'sulęcin',
    'sulęczyno',
    'sulików',
    'sulmierzyce',
    'sułkowice',
    'sułoszowa',
    'sułów',
    'supraśl',
    'suraż',
    'susiec',
    'susz',
    'suszec',
    'suwałki',
    'swarzędz',
    'swietajno',
    'swiętajno',
    'syców',
    'sypniewo',
    'syrynia',
    'szadek',
    'szaflary',
    'szamocin',
    'szamotuły',
    'szarów',
    'szastarka',
    'szczaniec',
    'szczawnica',
    'szczawnica niżna',
    'szczawno-zdrój',
    'szczebrzeszyn',
    'szczecin',
    'szczecinek',
    'szczekociny',
    'szczepanowice',
    'szczepanów',
    'szczerbice',
    'szczerców',
    'szczęść boże',
    'szczucin',
    'szczuczyn',
    'szczurowa',
    'szczutowo',
    'szczyrk',
    'szczytna',
    'szczytnica',
    'szczytno',
    'szelków',
    'szemud',
    'szepietowo',
    'szerzyny',
    'szklarska poręba',
    'szlachta',
    'szlichtyngowa',
    'szprotawa',
    'szreńsk',
    'sztum',
    'sztumskie przedmicście',
    'sztutowo',
    'szubin',
    'szumowo',
    'szwederowo',
    'szydłowiec',
    'szydłowo',
    'szydłów',
    'szymany',
    'szynwałd',
    'szyszków',
    'ściegny',
    'ścinawa',
    'ślemień',
    'ślesin',
    'śliwice',
    'śmigiel',
    'śmiłowo',
    'śniadowo',
    'śrem',
    'środa śląska',
    'środa wielkopolska',
    'śródmieście',
    'świątniki górne',
    'świdnica',
    'świdnik',
    'świdnik mały',
    'świdwin',
    'świebodzice',
    'świebodzin',
    'świecie',
    'świecie nad osą',
    'świedziebnia',
    'świekatowo',
    'świeradów-zdrój',
    'świercze',
    'świerczewo',
    'świerczów',
    'świerklaniec',
    'świerklany',
    'świerklany dolne',
    'świerklany górne',
    'świerzawa',
    'świerzno',
    'święciechowa',
    'święta katarzyna',
    'świętajno',
    'świętochłowice',
    'świlcza',
    'świnice warckie',
    'świnna',
    'świnobród',
    'świnoujście',
    'tajęcina',
    'tarczyn',
    'targanice',
    'targowisko',
    'tarłów',
    'tarnawatka',
    'tarnobrzeg',
    'tarnogród',
    'tarnowiec',
    'tarnowo podgórne',
    'tarnowskie góry',
    'tarnów',
    'tarnów opolski',
    'tarnówka',
    'tczew',
    'tczów',
    'telatyn',
    'tenczynek',
    'teresin',
    'terespol',
    'tereszpol',
    'tłuchowo',
    'tłuszcz',
    'tokarnia',
    'tolkmicko',
    'tomaszkowice',
    'tomaszów lubelski',
    'tomaszów mazowiecki',
    'tomice',
    'toporzysko',
    'topólka',
    'torun county',
    'toruń',
    'toruń północny',
    'torzym',
    'toszek',
    'trablice',
    'trawniki',
    'trąbki',
    'trąbki wielkie',
    'trojanów',
    'troszyn',
    'truskaw',
    'truskolasy',
    'tryńcza',
    'trzciana',
    'trzcianka',
    'trzciel',
    'trzcinica',
    'trzciniec dolny',
    'trzcińsko zdrój',
    'trzebiatów',
    'trzebiechów',
    'trzebiegoszcz',
    'trzebiel',
    'trzebielino',
    'trzebieńczyce',
    'trzebieszów',
    'trzebinia',
    'trzebnica',
    'trzebownisko',
    'trzebunia',
    'trzemeszno',
    'trzemeśnia',
    'trzydnik duży',
    'tuchola',
    'tuchomie',
    'tuchów',
    'tuczępy',
    'tuczna',
    'tuczno',
    'tuliszków',
    'tułowice',
    'tuplice',
    'turczynek',
    'turek',
    'turobin',
    'turośń kościelna',
    'turza śląska',
    'turze pole',
    'tuszyn',
    'twardawa',
    'twardogóra',
    'twierdza',
    'tworki',
    'tworków',
    'tworóg',
    'tychowo',
    'tychy',
    'tyczyn',
    'tykocin',
    'tymbark',
    'tyniec mały',
    'tyrawa wołoska',
    'tyszowce',
    'uciechów',
    'udanin',
    'uherce mineralne',
    'ujazd',
    'ujsoły',
    'ujście',
    'ulanów',
    'ulhówek',
    'ulica starowiejska',
    'ułęż',
    'uniejów',
    'unisław',
    'urszulin',
    'urzejowice',
    'urzędów',
    'urzuty',
    'ustka',
    'ustronie morskie',
    'ustroń',
    'ustrzyki dolne',
    'uście gorlickie',
    'uście ruskie',
    'uścimów stary',
    'wadowice',
    'wadowice górne',
    'waganiec',
    'waksmund',
    'walce',
    'walichnowy',
    'walim',
    'wałbrzych',
    'wałcz',
    'wapno',
    'warka',
    'warlubie',
    'warnice',
    'warsaw',
    'warszawa',
    'warszewo',
    'warta',
    'wartkowice',
    'wasilków',
    'waśniów',
    'wawrzeńczyce',
    'wąbrzeźno',
    'wąchock',
    'wągrowiec',
    'wąpielsk',
    'wąsosz',
    'wąwolnica',
    'wejherowo',
    'wejsuny małe',
    'werbkowice',
    'weremień',
    'wesoła',
    'węgierska górka',
    'węgliniec',
    'węglówka',
    'węgorzewo',
    'węgorzyno',
    'węgrów',
    'węgry',
    'węgrzce wielkie',
    'wiązownica',
    'wiązów',
    'widawa',
    'widuchowa',
    'wiechowice',
    'wieczfnia kościelna',
    'wielbark',
    'wieleń',
    'wielgie',
    'wielichowo',
    'wieliczka',
    'wieliszew',
    'wielka nieszawka',
    'wielka wieś',
    'wielki kack',
    'wielkie oczy',
    'wielopole skrzyńskie',
    'wielowieś',
    'wieluń',
    'wieniawa',
    'wieprz',
    'wieruszów',
    'wierzawice',
    'wierzbica',
    'wierzbinek',
    'wierzbna',
    'wierzbno',
    'wierzchlas',
    'wierzchosławice',
    'wierzchowo',
    'wierzchucino',
    'wieszowa',
    'wietrzychowice',
    'więcbork',
    'większyce',
    'wijewo',
    'wilamowice',
    'wilcza',
    'wilczogóra',
    'wilczyce',
    'wilczyn',
    'wilga',
    'wilkołaz',
    'wilkowice',
    'wilków',
    'winiary',
    'winnica',
    'wińsko',
    'wiskitki',
    'wisła',
    'wisznia mała',
    'wisznice',
    'wiślica',
    'wiśniew',
    'wiśniewo',
    'wiśniowa',
    'witanowice',
    'witaszyce',
    'witkowice',
    'witkowo',
    'witnica',
    'witonia',
    'wizna',
    'wleń',
    'władysławowo',
    'władysławów',
    'własna',
    'włocławek',
    'włodawa',
    'włodowice',
    'włosienica',
    'włoszakowice',
    'włoszczowa',
    'wodąca',
    'wodynie',
    'wodzierady',
    'wodzisław',
    'wodzisław śląski',
    'wohyń',
    'wojakowa',
    'wojaszówka',
    'wojciechowice',
    'wojciechów',
    'wojcieszków',
    'wojcieszów',
    'wojcieszów górny',
    'województwo dolnośląskie',
    'województwo kujawsko-pomorskie',
    'województwo lubelskie',
    'województwo lubuskie',
    'województwo łódzkie',
    'województwo małopolskie',
    'województwo mazowieckie',
    'województwo opolskie',
    'województwo podkarpackie',
    'województwo podlaskie',
    'województwo pomorskie',
    'województwo śląskie',
    'województwo świętokrzyskie',
    'województwo warmińsko-mazurskie',
    'województwo wielkopolskie',
    'województwo zachodniopomorskie',
    'wojkowice',
    'wojnicz',
    'wojsławice',
    'wojstawice',
    'wola',
    'wola batorska',
    'wola dębińska',
    'wola filipowska',
    'wola jachowa',
    'wola karczewska',
    'wola kożuszkowa',
    'wola krzysztoporska',
    'wola raciążek',
    'wola radziszowska',
    'wola rębkowska',
    'wola sernicka',
    'wola uhruska',
    'wola zabierzowska',
    'wola żarczycka',
    'wolanów',
    'wolbórz',
    'wolbrom',
    'wolin',
    'wolsztyn',
    'wołczyn',
    'wołomin',
    'wołowice',
    'wołów',
    'woźniki',
    'wożniki',
    'wólka',
    'wólka kożuchowska',
    'wólka niedźwiedzka',
    'wólka pełkińska',
    'wólka podleśna',
    'wólka tanewska',
    'wręczyca wielka',
    'wrocław',
    'wrocław pracze',
    'wronki',
    'wróblew',
    'wrząsowice',
    'września',
    'wschowa',
    'wydminy',
    'wymiarki',
    'wymysłów',
    'wymyślanka',
    'wyry',
    'wyrzysk',
    'wysoka',
    'wysoka głogowska',
    'wysoka strzyżowska',
    'wysokie',
    'wysokie mazowieckie',
    'wyszki',
    'wyszków',
    'wyszogród',
    'wyśmierzyce',
    'wyżne',
    'wzgórze św. maksymiliana',
    'zabełków',
    'zabierzów',
    'zabierzów bocheński',
    'zabłocie',
    'zabłudów',
    'zabornia',
    'zaborze',
    'zabór',
    'zabrze',
    'zabrzeg',
    'zadział',
    'zadzim',
    'zagnańsk',
    'zagórnik',
    'zagórów',
    'zagórz',
    'zagórze',
    'zagórzyce',
    'zagórzynek',
    'zagrodno',
    'zagrody',
    'zajezierze',
    'zakliczyn',
    'zaklików',
    'zakopane',
    'zakroczym',
    'zakrzew',
    'zakrzewice',
    'zakrzewo',
    'zakrzów',
    'zakrzówek',
    'zalas',
    'zalesie',
    'zalesie górne',
    'zaleszany',
    'zalewo',
    'załuski',
    'zamarski',
    'zambrów',
    'zamch',
    'zamłynie',
    'zamość',
    'zanęcin',
    'zaniemyśl',
    'zapolice',
    'zarszyn',
    'zarzecze',
    'zasanie',
    'zastawa',
    'zator',
    'zatory',
    'zawadzkie',
    'zawichost',
    'zawidów',
    'zawidz',
    'zawiercie',
    'zawiercie nowe',
    'zawoja',
    'zazamcze',
    'ząbki',
    'ząbkowice śląskie',
    'zbarz',
    'zbąszynek',
    'zbąszyń',
    'zblewo',
    'zbójna',
    'zbójno',
    'zbrosławice',
    'zbuczyn',
    'zbytków',
    'zdrojki',
    'zduny',
    'zduńska wola',
    'zdziechowice drugie',
    'zdzieszowice',
    'zebrzydowice',
    'zelów',
    'zembrzyce',
    'zębowice',
    'zgierz',
    'zgłobień',
    'zgoda',
    'zgorzelec',
    'zielona góra',
    'zielonka',
    'zielonki',
    'ziębice',
    'zimnodół',
    'zławieś wielka',
    'złocieniec',
    'złoczew',
    'złota',
    'złotniki',
    'złotniki kujawskie',
    'złotoryja',
    'złotów',
    'złoty stok',
    'zmiennica',
    'zubardź',
    'zubrzyca dolna',
    'zubrzyca górna',
    'zwierzyniec',
    'zwierzyń',
    'zwoleń',
    'zyglinek',
    'żabia wola',
    'żabieniec',
    'żabnica',
    'żabno',
    'żagań',
    'żarki',
    'żarki-letnisko',
    'żarnów',
    'żarów',
    'żary',
    'żegocina',
    'żelazków',
    'żelechlinek',
    'żelechów',
    'żelistrzewo',
    'żerków',
    'żernica',
    'żerniki wrocławskie',
    'żłobizna',
    'żmigród',
    'żnin',
    'żołynia',
    'żory',
    'żółkiewka',
    'żórawina',
    'żukowo',
    'żurawica',
    'żurawiczki',
    'żuromin',
    'żurowa',
    'żychlin',
    'żyraków',
    'żyrardów',
    'żyrzyn',
    'żywiec'
];